services:
  workout-tracker:
    image: ghcr.io/kavith-k/workout-tracker:latest
    container_name: workout-tracker
    ports:
      - '6789:3000'
    volumes:
      - docker-config/workout-tracker:/data
    restart: unless-stopped
